const express = require("express");
const { body } = require("express-validator");
const { register, login, me } = require("../controllers/authController");
const { protect } = require("../middleware/authMiddleware");
const validate = require("../middleware/validateMiddleware");
const router = express.Router();
router.post("/register", [ body("name").trim().isLength({min:2}).withMessage("Name must be at least 2 characters."), body("email").isEmail().withMessage("Valid email is required.").normalizeEmail(), body("password").isLength({min:6}).withMessage("Password must be at least 6 characters."), body("confirmPassword").custom((value,{req})=>value===req.body.password).withMessage("Passwords do not match.") ], validate, register);
router.post("/login", [ body("email").isEmail().withMessage("Valid email is required.").normalizeEmail(), body("password").notEmpty().withMessage("Password is required.") ], validate, login);
router.get("/me", protect, me);
module.exports = router;
